# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnb" do
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/lnb"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lnb"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.8.1/lnb_0.8.1_Darwin_x86_64.tar.gz"
      sha256 "b2ff9194ae3517d1824482d8afd1685d11b403e95fb1749506833d75cb904b7f"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.8.1/lnb_0.8.1_Darwin_arm64.tar.gz"
      sha256 "7638d913f9bcf5229e0582c52b7664de2b8fc50cde3dabe6918f639e2ff2cb48"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.8.1/lnb_0.8.1_Linux_x86_64.tar.gz"
      sha256 "d928b06e9d9d0d3eeb980dabe8da2c4fea1a33d470bea80c4f1ae27cdf82ea38"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.8.1/lnb_0.8.1_Linux_arm64.tar.gz"
      sha256 "c1a4d9127116942aeaee23dbee27d6910a64aa133749e75eec6592b9ac67e063"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lnb"]
    end
  end

  # No zap stanza required
end
