# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnb" do
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/lnb"
  version "0.3.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lnb"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.3.16/lnb_0.3.16_Darwin_x86_64.tar.gz"
      sha256 "b823281e40e030459b6d0fd2c655d6ba25d5c88cf45474a3e2d3656e52f9a280"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.3.16/lnb_0.3.16_Darwin_arm64.tar.gz"
      sha256 "d6e00c85c0d2903288936454c0ed4afb1ca581ac21f372e28fcf72f2f97442a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.3.16/lnb_0.3.16_Linux_x86_64.tar.gz"
      sha256 "ab06b4c99d1ad09bcfa7bab6fbf37a89fe9cd11a975f9c0eed46b5090fb1595e"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.3.16/lnb_0.3.16_Linux_arm64.tar.gz"
      sha256 "0fbc77d8925bab69c4df4f18991e5cb6bd8859bab12474e9b30d3be1e68b3a13"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lnb"]
    end
  end

  # No zap stanza required
end
