# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnb" do
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/lnb"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lnb"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.7.0/lnb_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "7931d7913153299b34520a81c36f6b80028cba7bebdd67cd004928de76d0124e"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.7.0/lnb_0.7.0_Darwin_arm64.tar.gz"
      sha256 "aa67d61b5d046ce54bda7b5473e3f721fc5ab557c65c295f93a03b4117b85b8f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.7.0/lnb_0.7.0_Linux_x86_64.tar.gz"
      sha256 "03a7b8645dab148b1fb08ffe04a948177103064f870fdd48309a6af9a984eef3"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.7.0/lnb_0.7.0_Linux_arm64.tar.gz"
      sha256 "c044efb2ac178b967b42bbaa461f1b72d11b5ba22742a8c628dc5c636aa014fd"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lnb"]
    end
  end

  # No zap stanza required
end
